### PR TITLE
prefixed variable names with `$local:`

### PR DESCRIPTION
**Pull request by peterstadler**
Hi Martin,

I needed to add those variable prefixes to make it work with my eXist installation (I'm running a dev build from Sept. 2016 on a Mac). Do those variable declarations really work for you without the prefixes?

### CODE REVIEW

**Comment by martindholmes** [comment]
Hi Peter,

Everything does work fine for me without the prefix, in 3.0 RC1. I was under the impression that prefixes were only required in a module, whereas this is not a module (you'll see all the variables in codesharing_config.xql are prefixed). I don't have any objection to the prefixes, but I'd like to know first whether this is a bug in the particular build of eXist you're using, or an intentional change in behaviour. Do you know?

**Comment by peterstadler** [comment]
Ah, ok, I nailed it down to the default element namespace declaration. If I take this out, no complaints anymore …
Otherwise I get: 
```xml
<exception>
  <path>/db/apps/codesharing/codesharing.xql</path>
  <message>err:XPDY0002 variable '$inputOutputType' is not set. [at line 50, column 46, source: /db/apps/codesharing/codesharing.xql]</message>
</exception>
```

**Comment by martindholmes** [comment]
That's even weirder. That has to be an eXist bug, surely? The variable is set:

`declare variable $inputOutputType := request:get-parameter('outputType', 'xml');`

How can it wind up not set, unless it's being set to an empty string in your controller.xql?

**Comment by martindholmes** [comment]
Peter, could you try 1.0.2 and see if that has the same issue?

**Comment by peterstadler** [comment]
No, sorry, now it's complaining about line 69: "err:XPDY0002 variable '$verb' is not set".
It seems to stumble about the first reference to a global variable.

**Comment by martindholmes** [comment]
OK, I think I'd like to pin this down before going any further. Which of these seems most likely?

- eXist has decided that unprefixed variables are no longer allowed? If so, an awful lot of my existing code will need to be updated.
- The version of eXist you have has a specific bug which is either fixed in a future version or should be reported.
- There is a configuration setting somewhere in eXist that says "do not allow unprefixed variables", and either you've set it, or its default setting has been changed.

**Comment by martindholmes** [comment]
I think it might be related to this:

https://github.com/eXist-db/exist/issues/359

**Comment by peterstadler** [comment]
While I get no errors with the provided code snippet from eXist-db/exist#359 it still looks like an eXist bug :( 
So, feel free to discard the pull request but be warned that some users might experience trouble with the codesharing xar ;)

**Comment by martindholmes** [comment]
We should test it with the nightly build to see if it's fixed; if not, we should report it. Not knowing what causes it means that we'd be working around it in an arbitrary way that might not work in the long term.

**Pull request closed without merging**
